initial_cash: 1000000
commission_rate: 0.0003
minimum_commission: 5
stock_sell_stamp_duty_rate: 0.0005
slippage_rate: 0.0005
lot_size: 100
signal_price_adjustment: qfq
execution_price_adjustment: raw
